import raw from './changelog.json';

export type ReleaseNote = {
  /** "Major" | "Minor" | "Patch", as changesets classified it. */
  kind: string;
  /** First sentence, stripped of markdown — the collapsed summary line. */
  headline: string;
  /** Full changeset body, markdown. */
  body: string;
  /** Packages this note was written into, sorted. */
  packages: string[];
};

export type Release = {
  version: string;
  /** ISO date from the release tag, or null when not yet tagged. */
  date: string | null;
  packageCount: number;
  notes: ReleaseNote[];
};

/**
 * Generated by `npm run gen:changelog` from the per-package CHANGELOG.md files.
 * Do not hand-edit app/changelog.json — re-run the script after a release.
 */
export const releases: Release[] = raw as Release[];

export const latestVersion = releases[0]?.version ?? '';
