import raw from './changelog.json';

export type ReleaseNote = {
  /** "Major" | "Minor" | "Patch", as changesets classified it. */
  kind: string;
  /** First sentence, stripped of markdown — the collapsed summary line. */
  headline: string;
  /** Full changeset body, markdown. */
  body: string;
  /** Packages this note was written into, sorted. */
  packages: string[];
};

export type Release = {
  version: string;
  /** ISO date from the release tag, or null when not yet tagged. */
  date: string | null;
  /**
   * True for a release assembled from changesets that are merged but not yet
   * versioned or published. The version is the one changesets will pick.
   */
  pending: boolean;
  packageCount: number;
  notes: ReleaseNote[];
};

/**
 * Generated by `npm run gen:changelog` from the per-package CHANGELOG.md files.
 * Do not hand-edit app/changelog.json — re-run the script after a release.
 */
export const releases: Release[] = raw as Release[];

/**
 * The newest version actually on npm. A pending release is deliberately skipped:
 * telling someone to install a version that does not exist yet is worse than
 * showing them one release behind.
 */
export const latestVersion = releases.find((r) => !r.pending)?.version ?? '';
